# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 792cf4930932270c39e4db55de2a77718ec253ef1d58ef43e3a2a86471fbbe850f35d6dbece5a94b43f2a57756076acb0703d1a33f8cff44c2fbdd1a6128c9a9

test:
  secret_key_base: 339eaaff38bda942fd674dd948181ba43e518ca4220f6f1508a6a3402944b9c81399eb31167e9f951560ccdfa7856bb41ee23dccdcd58257770dbe7a939d974c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
